apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sx-cnp-demo-app"
  annotations:
    github.com/project-slug: suxess-it/sx-cnp-demo-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=prod-demo-app'
    argocd/app-name: "prod-demo-app"
    backstage.io/techdocs-ref: dir:.
    kubecost.com/deployment-name: prod-demo-app-podtato-head-left-leg
    grafana/dashboard-selector: "(tags @> '4GoldenSignals')"
    kargo-project: "https://kargo-127-0-0-1.nip.io/project/kargo-demo-app"
    grafana/overview-dashboard: "https://kargo-127-0-0-1.nip.io/project/kargo-demo-app"
spec:
  type: service
  lifecycle: experimental
  owner: sx-authors
